services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:alpine
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    network_mode: bridge
    restart: on-failure
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false

volumes:
  jenkins_home:
    name: jenkins_home