services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper/zookeeper.properties:/opt/kafka/config/zookeeper.properties
  
  broker1:
    build: kafka
    container_name: broker1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    volumes:
      - ./kafka/server.properties:/opt/kafka/config/server.properties
 
  # Need to have seperate advertised listeners for each broker
  # broker2:
  #   build: kafka
  #   container_name: broker2
  #   ports:
  #     - "9091:9092"
  #   depends_on:
  #     - zookeeper
  #   volumes:
  #     - ./kafka/server.properties:/opt/kafka/config/server.properties