# TODO:
# - Persisted volume

apiVersion: v1
kind: Pod
metadata:
  name: docker-registry
  labels:
    purpose: storage
    app: docker-registry
spec:
  containers:
    - name: docker-registry
      image: docker.io/registry:2.8.1
      ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata: 
  name: docker-registry-nodeport
spec:
  type: NodePort
  selector:
    app: docker-registry
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
