# TODO:
# - Persisted volume
# - image in private image registry

apiVersion: v1
kind: Pod
metadata:
  name: gogs
  labels:
    purpose: devops
    app: gogs
spec:
  containers:
    - name: gogs
      image: docker.io/gogs/gogs:0.13
      ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: gogs-nodeport
spec:
  type: NodePort
  selector:
    app: gogs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000