# TODO:
# - Persisted volume
# - image in private image registry

apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    purpose: devops
    app: jenkins
spec:
  containers:
    - name: jenkins
      image: docker.io/jenkins/jenkins:alpine
      ports: 
        - containerPort: 8080
        - containerPort: 50000
      env:
        - name: JAVA_OPTS 
          value: "-Djenkins.install.runSetupWizard=false"
---
apiVersion: v1
kind: Service
metadata: 
  name: jenkins-nodeport
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
